version: '3'
networks:
  default:
    driver: bridge
        
services:
  ethdb:
    image: "mysql:8.0" 
    ports:
      - "3306:3306"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
    networks: 
      - default
    privileged: true
    volumes:
      - "./mysql/conf/my.cnf:/etc/my.cnf"
      - "./mysql/init:/docker-entrypoint-initdb.d/"
      - "./data/ethdb:/var/lib/mysql"
  bfbackend:
    image: "tscel/bfbackend:latest"
    restart: always
    networks:
      - default
    ports:
      - "8088:8088"
    entrypoint: bfbackend --config /root/config.yml
    volumes:
      - "./config/bfbackend.yml:/root/config.yml"
    depends_on:
      - ethdb

  caddy:
    image: caddy:latest
    restart: unless-stopped
    networks:
      - default
    environment:
      - XDG_CONFIG_HOME=/config
      - XDG_DATA_HOME=/data
      - CADDY_ADMIN=0.0.0.0:2019
    ports:
      - "35770:80"
      - "35771:443"
      - "32019:2019"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/root:/srv
      - ./caddy/data:/data
      - ./caddy/config:/config
      - ./web:/web